import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/NavBar/NavBar";
// import HiddenNavBar from "@/components/hidden_navbar/HiddenNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <HiddenNavBar> */}
        {/* <Navbar/> */}
        {/* </HiddenNavBar> */}
        {children}
        </body>
    </html>
  );
}
